### ISSUE TITLE
Add rate limiter to server

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#10]
Implement rate limiting on the server using express-rate-limit to prevent abuse of API endpoints. Set appropriate thresholds for each route.

**Reference:**
- [Express Rate Limiting](https://www.npmjs.com/package/express-rate-limit)

**Comment by geekyharsh05** [comment]
@dead8309 Can you please assign me?

**Comment by Tony-ArtZ** [comment]
> @dead8309 Can you please assign me?

@geekyharsh05  Consider this yours, Happy hacktoberfest!
