### ISSUE TITLE
Add a /verify route for JWT token verification

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#11]
Create a /verify route that verifies the provided JWT token and returns an appropriate response indicating if the token is valid or expired.

**Reference:**
- [JWT Authentication in Express](https://www.geeksforgeeks.org/how-to-implement-jwt-authentication-in-express-js-app/)

**Comment by Utkarsh-2005** [comment]
Assign

**Comment by dead8309** [comment]
🫡
