### ISSUE TITLE
Add CORS protection to the server

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#13]
Add CORS middleware to the server to handle cross-origin requests. Configure it appropriately to secure access based on domains.

**Reference:**
- [CORS in Express](https://dev.to/speaklouder/how-to-configure-cors-in-nodejs-with-express-11h)

**Comment by Rasheedatj** [comment]
Hi @dead8309 I have gone through your codebase, the middleware will be added in the index.js file. Kindly assign this task to me so that I can complete it asap

**Comment by dead8309** [comment]
It's yours 😄

**Comment by Rasheedatj** [comment]
what's up with the emoji?

**Comment by Rasheedatj** [comment]
@dead8309  https://github.com/MLSAKIIT/devblogs-backend/pull/19

Kindly review my PR

**Comment by dead8309** [comment]
Thanks for contributing @Rasheedatj :heart:
