### ISSUE TITLE
Implement proper logging to the server

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#14]
Set up a logging system using libraries like Winston or Morgan to log errors, warnings, and general request logs for the server.

**Reference:**
- [Express Error Handling](https://expressjs.com/en/guide/error-handling.html)

**Comment by geekyharsh05** [comment]
@dead8309 Can we use morgan for logging?

**Comment by Tony-ArtZ** [comment]
@geekyharsh05  yes, you can! do you want me to assign this to you?

**Comment by geekyharsh05** [comment]
@Tony-ArtZ Yes i will be more than happy to work on it.

**Comment by Tony-ArtZ** [comment]
> @Tony-ArtZ Yes i will be more than happy to work on it.

Alright! Assigned, Happy Hacktoberfest!

**Comment by dead8309** [comment]
Added in #27
