### ISSUE TITLE
Set up /register route with hashed password

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#17]
Implement the /register route in the backend API using Express. Ensure passwords are hashed using bcrypt or a similar library before saving them in the database.

**Reference**:

- [JWT Authentication in Express](https://www.geeksforgeeks.org/how-to-implement-jwt-authentication-in-express-js-app/)
- [Mongoose with Express](https://www.youtube.com/watch?v=_7UQPve99r4)

**Comment by KartikMouli** [comment]
I would like to work on this !

**Comment by dead8309** [comment]
Fixed in #23
