### ISSUE TITLE
Set up pagination on GET /get-blogs route

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#2]
Implement pagination on the GET /get-blogs route. Use query parameters for the page and limit, and ensure data is returned based on these parameters.

**Reference:**
- [Pagination with Mongoose](https://javascript.works-hub.com/learn/how-to-create-a-paginated-api-with-mongodb-and-node-js-6e1e3)

**Comment by Tony-ArtZ** [comment]
Sure! best of luck
