### ISSUE TITLE
Feat: add Docker & Compose Support

### ISSUE THREAD

**Issue by geekyharsh05** [MLSAKIIT/devblogs-backend#28]
Implement a Dockerfile for containerizing the application and a docker-compose.yml file to manage multi-container setups for seamless local development.

- [ ] Dockerfile for dev mode
- [ ] Docker compose file

**Comment by pandeyashu08** [comment]
@Tony-ArtZ can you please assign me

**Comment by Tony-ArtZ** [comment]
@geekyharsh05 do you wish to work on this or should I assign @pandeyashu08 ?

**Comment by dead8309** [comment]
Added in #41
