### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Utkarsh-2005** [MLSAKIIT/devblogs-backend#38]
- The folder structure of the project is not up to date.
- The different routes also need to be updated.

**Comment by swastik-apk** [comment]
@Utkarsh-2005 Can you elaborate what you mean by "different routes need to be updated" ?

**Comment by Utkarsh-2005** [comment]
@swastik-apk , I am referring to the api routes listed in our Readme, for example /change-password route has not been mentioned. Kindly do so and make other similar updations.

**Comment by swastik-apk** [comment]
@dead8309 @Tony-ArtZ Can you assign this issue to me ?
