### ISSUE TITLE
Set up request body validation on /create-blog route using Joi

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#5]
Add request body validation on the /create-blog route using Joi. Validate required fields such as title, content, and tags before saving to the database.

**Reference:**
- [Joi Validation in Express](https://abbaslanbay.medium.com/introduction-to-joi-validation-in-node-js-express-c33eba38f4ae)

**Comment by Tony-ArtZ** [comment]
> Hello @dead8309 Can you assign this issue to me?

Assigned ! Happy Hacktoberfest!

**Comment by Utkarsh-2005** [comment]
@Pratik00019 are you working on this issue?

**Comment by Pratik00019** [comment]
Yes @Utkarsh-2005 , I am working on it
