### ISSUE TITLE
Feature: Add a seeding to db

### ISSUE THREAD

**Issue by pantharshit007** [MLSAKIIT/devblogs-backend#53]
**Is your feature request related to a problem? Please describe.**
whenever new developer set the repo they have to create their own data to test for any new feature

**Describe the solution you'd like**
to tackle this what usually does is a seed file is created as its name suggests on the initial run of the server we will seed some demo data into our database so that developers don't have to create test data.

**Describe alternatives you've considered**

**Additional context**

**Comment by pantharshit007** [comment]
also please close the existing issues i thought they were pending from last 2 weeks you have merged there changes but haven't closed the issues yet.

**Comment by pantharshit007** [comment]
@sohambuilds @SourasishBasu @rycerzes  anyone?

**Comment by dead8309** [comment]
> also please close the existing issues i thought they were pending from last 2 weeks you have merged there changes but haven't closed the issues yet.

Which issue numbers ?

**Comment by pantharshit007** [comment]
@dead8309  could you check i have made the pr and do add the tag

all of these issues are merged
![image](https://github.com/user-attachments/assets/f41c2412-eaf2-4294-a4b8-9c38821a5b54)
