### ISSUE TITLE
Check if user already exists and handle error on /register route

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#7]
Modify the /register route to check if a user already exists in the database. Return an appropriate error response if a user with the same email already exists.

**Reference:**
- [Mongoose with Express](https://www.mongodb.com/resources/languages/express-mongodb-rest-api-tutorial)

**Comment by Abhineetsahay** [comment]
i like to take it

**Comment by Abhineetsahay** [comment]
Hi i like to handle it
