### ISSUE TITLE
Set up route protection on /create-blog route using middleware

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#9]
Add middleware to protect the /create-blog route. Ensure only authenticated users (with a valid JWT token) can access this route.

**Reference:**
- [Route Protection using Middleware](https://dvmhn07.medium.com/jwt-authentication-in-node-js-a-practical-guide-c8ab1b432a49)

**Comment by Utkarsh-2005** [comment]
I would like to work on this
